obstacle_range: 5.0
raytrace_range: 5.0
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.1
inflation_radius: 0.60

observation_sources: laser_scan_sensor #point_cloud_sensor

# marking - add obstacle information to cost map
# clearing - clear obstacle information to cost map
laser_scan_sensor: {data_type: LaserScan, topic: /base_scan, marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}

